token:
  expiration_time: 86400000
  secret: '{cipher}AQBeaVVc2BgTz7PxDNNkg9c7cU2zzrI8Vk4petmt8/EoGSLn4ZEjxBoGQGgfDFh7bENdj9ocGENk90ZTe5XERsPNQal0PKsSfXPsyBWfky3gPBGz+kT26NyLbKhMTUWfJ6fE0dOMa8EiiGUZjWyENW2YDrFj4ntYRPPPQZDlC3NflSOH5I1b12+Uo43dDocWf1ZM+COziwZQfXAL/q8plI7z3bry8uDFpq0cH4EccyLN9i0yfTDTFUC8etv0GwwPxv2U+Hq6+qRnNcgZXsSs4LsNcpk8g0OVRvBpR03/71hc0s8YZDFpU4YFk4SjUXldVxkeaLXW21mgLtqmuWKnH0hWnP7wDPYtxGfbxMVs28NzzIzkTcSFyzFNZUD0qekngQVJGWwe65bMBvk38KPaiV77'

gateway:
  ip: 172.18.0.1
