spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3308/deploymentService
    username: yeaseul
    password: '{cipher}AQBeISvkwG3nbW0zQeR3zRNwYtM2a1XJnhE5O777EymRb0hjcEGH0YyEULCdv5Swt7SFtb/uyQ9PZx7Cwh42WvaLFluRhj2oWmBqrDhr7AHppUwFd3oSUldPmvYAhBmKkmdutVTZ49/kP7n3Rvf6GMpE0sCH3kBbqOplp80FSoWea507lT3yDJC/dNhZ3IDLsUSa4x4UjfMTK7/trnx7mn545FYA0LTgAzIboHbM6qOZqQvkyukViF4cMqiB6EK8o97Lh4GawjwpMxTeF4WZo0mQeyqJ6hrkSWIJzWc1ZBnjfXcOUsrdiquwP8rIrUxVnuDG/+3tc4/r89xQwxezpHh06DxnoQop8IMMacDRgOQJkYaUd7yY5hgwk3TyKA0Q2xs='

